services:
  guacamole:
    image: guacamole/guacamole
    restart: always
    ports:
      - "8080:8080"
    links:
      - guacd
    volumes:
      - ./guacamole_extensions:/opt/guacamole/extensions
    environment:
      EXTENSION_PRIORITY: noauth
      LOG_LEVEL: DEBUG

  guacd:
    image: guacamole/guacd
    restart: always